---
# Label: ansible_redhat_sso_keystore
# Title: create the Ansible template for the Red Hat SSO keystore in OpenShift
# Mission: create the Ansible defaults for the Red Hat SSO keystore in OpenShift
# Milestone: Automate SSO Deployment
# Column: Automate SSO Deployment

apiVersion: v1
kind: Secret
type: Opaque
data:
  https-keystore.jks: >-
    {{SSL_JKS_BASE64}}
  jgroups.jceks: >-
    {{SSL_JCEKS_BASE64}}
  keystore.jks: >-
    {{SSL_JKS_BASE64}}
