---
# Label: project_openshift_defaults
# Title: create the Ansible defaults for deploying the application to OpenShift
# Mission: create the Ansible defaults for deploying the application to OpenShift
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment

####################
# Certbot defaults #
####################

COMPUTATE_CERTBOT_DOMAIN_NAME: "..."

######################
# OpenShift defaults #
######################

# The OpenShift base URL where applications will be deployed.
REDHAT_OPENSHIFT_HOST: https://api.pro-us-east-1.openshift.com
# The OpenShift secret token to grant access to OpenShift (https://api.pro-us-east-1.openshift.com/oauth/token/request).
REDHAT_OPENSHIFT_TOKEN: "..."
# The OpenShift namespace where applications will be deployed.
REDHAT_OPENSHIFT_NAMESPACE: "mynamespace"

######################
# Zookeeper defaults #
######################

# The default port that Zookeeper runs to manage the cluster.
ZOOKEEPER_PORT: 2181
# The Zookeeper OpenShift base URL where Zookeeper will be deployed.
ZOOKEEPER_HOST: "{{REDHAT_OPENSHIFT_HOST}}"
# The Zookeeper OpenShift secret token to grant access to OpenShift (https://api.pro-us-east-1.openshift.com/oauth/token/request).
ZOOKEEPER_TOKEN: "{{REDHAT_OPENSHIFT_TOKEN}}"
# The Zookeeper OpenShift namespace where Zookeeper will be deployed.
ZOOKEEPER_NAMESPACE: "{{REDHAT_OPENSHIFT_NAMESPACE}}"
# The Zookeeper volume size for Zookeeper files.
ZOOKEEPER_VOLUME_SIZE: 1Gi
# The default hostname for the Zookeeper cluster manager.
ZOOKEEPER_HOST_NAME: "computate-zookeeper.{{ZOOKEEPER_NAMESPACE}}.svc"

#################
# Solr defaults #
#################

# The default port that Solr runs.
SOLR_PORT: 8983
# The Solr OpenShift base URL where Solr will be deployed.
SOLR_HOST: "{{REDHAT_OPENSHIFT_HOST}}"
# The Solr OpenShift secret token to grant access to OpenShift (https://api.pro-us-east-1.openshift.com/oauth/token/request).
SOLR_TOKEN: "{{REDHAT_OPENSHIFT_TOKEN}}"
# The Solr OpenShift namespace where Solr be deployed.
SOLR_NAMESPACE: "{{REDHAT_OPENSHIFT_NAMESPACE}}"
# The Solr volume size for Solr files.
SOLR_VOLUME_SIZE: 2Gi
# The default hostname for the Solr search engine.
SOLR_HOST_NAME: "computate-solr.{{SOLR_NAMESPACE}}.svc"

#######################
# PostgreSQL defaults #
#######################

# The default port that PostgreSQL runs.
POSTGRES_PORT: 5432
# The PostgreSQL OpenShift base URL where PostgreSQL will be deployed.
POSTGRES_HOST: "{{REDHAT_OPENSHIFT_HOST}}"
# The PostgreSQL OpenShift secret token to grant access to OpenShift (https://api.pro-us-east-1.openshift.com/oauth/token/request).
POSTGRES_TOKEN: "{{REDHAT_OPENSHIFT_TOKEN}}"
# The PostgreSQL OpenShift namespace where PostgreSQL be deployed.
POSTGRES_NAMESPACE: "{{REDHAT_OPENSHIFT_NAMESPACE}}"
# The PostgreSQL volume size for Solr files.
POSTGRES_VOLUME_SIZE: 1Gi
# The default hostname for the PostreSQL database.
POSTGRES_HOST_NAME: "postgres.{{POSTGRES_NAMESPACE}}.svc"
# The default username for the PostreSQL database.
POSTGRES_DB_USER: computate
# The default PostgreSQL database name.
POSTGRES_DB_NAME: opendatapolicing
# The default PostgreSQL database password.
POSTGRES_DB_PASSWORD: "..."

#####################################
# opendatapolicing global defaults #
#####################################

# The opendatapolicing OpenShift base URL where opendatapolicing will be deployed.
PROJECT_HOST: "{{ REDHAT_OPENSHIFT_HOST }}"
# The opendatapolicing OpenShift secret token to grant access to OpenShift (https://api.pro-us-east-1.openshift.com/oauth/token/request).
PROJECT_TOKEN: "{{ REDHAT_OPENSHIFT_TOKEN }}"
# The opendatapolicing OpenShift namespace where opendatapolicing be deployed.
PROJECT_NAMESPACE: "{{ REDHAT_OPENSHIFT_NAMESPACE }}"
# The base URL where the static files will point to.
PROJECT_STATIC_BASE_URL: "https://example.neocities.org"
# The number of background worker executors that may run.
PROJECT_NUMBER_EXECUTORS: 5
# The properties file where the SSL/TLS encryption is configured.
PROJECT_SSL_PROPERTIES_FILENAME: opendatapolicing-keystore.properties

#########################################
# opendatapolicing US English defaults #
#########################################

# The domain name of the site.
PROJECT_DOMAIN_NAME_ENUS: "example.com"
# The host name of the site.
PROJECT_SITE_HOST_NAME_ENUS: "opendatapolicing-dev.{{PROJECT_DOMAIN_NAME_ENUS}}"
# The port of the site.
PROJECT_SITE_PORT_ENUS: "10581"
# The base URL of the site.
PROJECT_SITE_BASE_URL_ENUS: "https://{{PROJECT_SITE_HOST_NAME_ENUS}}:{{PROJECT_SITE_PORT_ENUS}}"
# The Solr collection of the site.
PROJECT_SOLR_COLLECTION_ENUS: "site"
# The timezone of the site.
PROJECT_SITE_ZONE_ENUS: "America/Denver"
# The PostgreSQL database host name of the site.
PROJECT_DB_HOST_NAME_ENUS: "localhost"
# The PostgreSQL database user name of the site.
PROJECT_DB_USER_ENUS: computate
# The PostgreSQL database password of the site.
PROJECT_DB_PASSWORD_ENUS: "..."
# The PostgreSQL database name of the site.
PROJECT_DB_NAME_ENUS: opendatapolicing
# The Java main class of the site.
PROJECT_JAVA_MAIN_CLASS_ENUS: com.opendatapolicing.enus.vertx.MainVerticle
# The backup directory of the site.
PROJECT_BACKUP_DIR_ENUS: "{{ lookup('env', 'ODP_ANSIBLE_STATIC') }}/data/enUS"
# The restore directory of the site.
PROJECT_RESTORE_DIR_ENUS: /home/ctate/backup/opendatapolicing-dev/enUS

#################
# SMTP defaults #
#################

# The email SMTP host name.
EMAIL_HOST_NAME: smtp.example.com
# The email SMTP port.
EMAIL_PORT: 465
# The email SMTP from email address.
EMAIL_FROM: "..."
# Whether email SMTP SSL/TLS encryption is enabled.
EMAIL_SSL: true
# Whether email SMTP username password authentication is enabled.
EMAIL_AUTH: true
# The email SMTP username.
EMAIL_USER: "..."
EMAIL_PASSWORD: "..."

####################
# SSL/TLS defaults #
####################

# The keystore alias.
SSL_ALIAS: "{{PROJECT_DOMAIN_NAME_ENUS}}"
# The keystore directory.
SSL_KEYSTORE_PATH: /opt/keystore
# The keystore properties filename.
SSL_PROPERTIES_FILENAME: "{{PROJECT_SSL_PROPERTIES_FILENAME}}"
# The keystore filename.
SSL_JKS_FILENAME: "{{SSL_ALIAS}}.jks"
# The keystore path.
SSL_JKS_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_JKS_FILENAME}}"
# The certificate filename.
SSL_CRT_FILENAME: "{{SSL_ALIAS}}.crt"
# The certificate path.
SSL_CRT_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_CRT_FILENAME}}"
# The private key filename.
SSL_KEY_FILENAME: "{{SSL_ALIAS}}.key"
# The private key path.
SSL_KEY_PATH: "{{SSL_KEYSTORE_PATH}}/{{SSL_KEY_FILENAME}}"
# The p12 file password.
SSL_P12_PASSWORD: "..."
# The keystore file password.
SSL_JKS_PASSWORD: "{{SSL_P12_PASSWORD}}"
# The keystore file base64 encoded (base64 -w 0 /opt/keystore/computate.org.jks).
SSL_JKS_BASE64: "..."
# The jceks file base64 encoded (base64 -w 0 /opt/keystore/computate.org.jceks).
SSL_JCEKS_BASE64: "..."

#######################################
# OpenID Connect auth server defaults #
#######################################

# The Red Hat SSO OpenShift base URL where Red Hat SSO will be deployed.
SSO_HOST: "{{REDHAT_OPENSHIFT_HOST}}"
# The Red Hat SSO OpenShift secret token to grant access to OpenShift (https://api.pro-us-east-1.openshift.com/oauth/token/request).
SSO_TOKEN: "{{REDHAT_OPENSHIFT_TOKEN}}"
# The Red Hat SSO OpenShift namespace where Red Hat SSO be deployed.
SSO_NAMESPACE: "{{REDHAT_OPENSHIFT_NAMESPACE}}"
# The default username for the Red Hat SSO PostreSQL database.
SSO_DB_USERNAME: "..."
# The default Red Hat SSO PostgreSQL database password.
SSO_DB_PASSWORD: "..."
# The default Red Hat SSO PostgreSQL database name.
SSO_DB_DATABASE: root
# The Red Hat SSO HTTPS keystore alias.
SSO_HTTPS_NAME: "{{SSL_ALIAS}}"
# The Red Hat SSO HTTPS keystore file password.
SSO_HTTPS_PASSWORD: "{{SSL_JKS_PASSWORD}}"
# The Red Hat SSO JGroups keystore alias.
SSO_JGROUPS_ENCRYPT_NAME: "{{SSL_ALIAS}}"
# The Red Hat SSO JGroups keystore file password.
SSO_JGROUPS_ENCRYPT_PASSWORD: "{{SSL_JKS_PASSWORD}}"
# A Red Hat SSO JGroups cluster password.
SSO_JGROUPS_CLUSTER_PASSWORD: "..."
# A Red Hat SSO admin username.
SSO_ADMIN_USERNAME: "..."
# A Red Hat SSO admin password.
SSO_ADMIN_PASSWORD: "..."
SSO_REALM: "{{AUTH_REALM}}"
# A Red Hat SSO initial user username.
SSO_SERVICE_USERNAME: "..."
# A Red Hat SSO initial user password.
SSO_SERVICE_PASSWORD: "..."
# The Red Hat SSO truststore file password.
SSO_TRUSTSTORE_PASSWORD: "{{SSL_JKS_PASSWORD}}"
# The Red Hat SSO volume size for Solr files.
SSO_VOLUME_SIZE: 1Gi
# The default hostname for Red Hat SSO.
SSO_SITE_HOST_NAME: "sso.example.com"

# The Auth realm.
AUTH_REALM: EXAMPLE.COM
# The Auth client or resource.
AUTH_RESOURCE: example.com
# The Auth secret.
AUTH_SECRET: "..."
# The Auth URL.
AUTH_URL: https://sso.example.com/auth
