---
# Title: create the Ansible playbook for deploying the complete application locally
# Mission: create the Ansible playbook for deploying the complete application locally
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment

- name: Install the opendatapolicing source code and watch service on the target. 
  hosts: localhost
  vars: 
    PROJECT_NAME: opendatapolicing
    GITHUB_ORG: "{{ PROJECT_NAME }}"
    PROJECT_REPO: "git@github.com:{{ PROJECT_NAME }}/{{ PROJECT_NAME }}.git"
    PROJECT_SRC: "{{ playbook_dir }}"
  tasks: 
    - include_role:
        name: computate.computate_postgres
    - include_role:
        name: computate.computate_zookeeper
    - include_role:
        name: computate.computate_solr
    - include_role:
        name: computate.computate_project
      vars: 
        PROJECT_JAVA_PACKAGE: com.opendatapolicing.enus
        PROJECT_SERVICES: 
          - PROJECT_NAME: "{{ PROJECT_NAME }}"
            PROJECT_SRC: "{{ playbook_dir }}"
            PROJECT_JAVA_PACKAGE: com.opendatapolicing.enus

