---
# Label: project_login_tasks
# Title: create the Ansible tasks for logging into the application with a service account
# Mission: create the Ansible tasks for logging into the application with a service account
# Milestone: Data Backup/Restore
# Column: Data Backup/Restore

- name: Restore site access token
  uri:
    url: "{{ AUTH_URL }}/realms/{{ AUTH_REALM }}/protocol/openid-connect/token"
    method: POST
    url_username: "{{ AUTH_RESOURCE }}"
    url_password: "{{ AUTH_SECRET }}"
    force_basic_auth: true
    body_format: form-urlencoded
    body:
      grant_type: client_credentials
  register: AUTH_TOKEN

