---
# Label: project_openshift_tasks
# Title: create the Ansible tasks for deploying the application to OpenShift
# Mission: create the Ansible tasks for deploying the application to OpenShift
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment
- name: Install keystore secrets on OpenShift
  k8s:
    state: present
    name: opendatapolicing-keystore
    host: "{{PROJECT_HOST}}"
    api_key: "{{PROJECT_TOKEN}}"
    namespace: "{{PROJECT_NAMESPACE}}"
    definition: "{{ lookup('template', 'project_keystore.yml') }}"
    validate_certs: false
- name: Rollout deployment config
  shell: "oc login {{PROJECT_HOST}} --token={{REDHAT_OPENSHIFT_TOKEN}} && oc rollout latest dc/opendatapolicing -n {{ PROJECT_NAMESPACE }}"
