---
# Title: create the Ansible playbook for restoring all opendatapolicing data for each type
# Mission: create the Ansible playbook for restoring all opendatapolicing data for each type
# Milestone: Data Backup/Restore
# Column: Data Backup/Restore


- name: Sign in to the application through the SSO server
  hosts: "{{ target }}"
  connection: local
  vars_files:
    - "{{ ODP_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
  roles:
    - { role: project_login }

- name: Restore the opendatapolicing page-design data.
  hosts: "{{ target }}"
  connection: local
  vars_files:
    - "{{ ODP_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
  roles:
    - { role: project_restore, DATA_NAME_VAR: page-design, DATA_URI: /api/page-design }

- name: Restore the opendatapolicing html-part data.
  hosts: "{{ target }}"
  connection: local
  vars_files:
    - "{{ ODP_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
  roles:
    - { role: project_restore, DATA_NAME_VAR: html-part, DATA_URI: /api/html-part }

- name: Restore the opendatapolicing page-design data.
  hosts: "{{ target }}"
  connection: local
  vars_files:
    - "{{ ODP_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
  roles:
    - { role: project_restore, DATA_NAME_VAR: page-design, DATA_URI: /api/page-design }

#- name: Restore the opendatapolicing state data.
#  hosts: "{{ target }}"
#  connection: local
#  vars_files:
#    - "{{ ODP_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
#  roles:
#    - { role: project_restore, DATA_NAME_VAR: state, DATA_URI: /api/state }
#
#- name: Restore the opendatapolicing agency data.
#  hosts: "{{ target }}"
#  connection: local
#  vars_files:
#    - "{{ ODP_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
#  roles:
#    - { role: project_restore, DATA_NAME_VAR: agency, DATA_URI: /api/agency }
#
#- name: Restore the opendatapolicing traffic-stop data.
#  hosts: "{{ target }}"
#  connection: local
#  vars_files:
#    - "{{ ODP_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
#  roles:
#    - { role: project_restore, DATA_NAME_VAR: traffic-stop, DATA_URI: /api/traffic-stop }
#
#- name: Restore the opendatapolicing traffic-search data.
#  hosts: "{{ target }}"
#  connection: local
#  vars_files:
#    - "{{ ODP_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
#  roles:
#    - { role: project_restore, DATA_NAME_VAR: traffic-search, DATA_URI: /api/traffic-search }
#
#- name: Restore the opendatapolicing traffic-person data.
#  hosts: "{{ target }}"
#  connection: local
#  vars_files:
#    - "{{ ODP_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
#  roles:
#    - { role: project_restore, DATA_NAME_VAR: traffic-person, DATA_URI: /api/traffic-person }
#
#- name: Restore the opendatapolicing traffic-contraband data.
#  hosts: "{{ target }}"
#  connection: local
#  vars_files:
#    - "{{ ODP_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
#  roles:
#    - { role: project_restore, DATA_NAME_VAR: traffic-contraband, DATA_URI: /api/traffic-contraband }
#
#- name: Restore the opendatapolicing search-basis data.
#  hosts: "{{ target }}"
#  connection: local
#  vars_files:
#    - "{{ ODP_ANSIBLE_INVENTORY }}/vaults/{{ VAULT_ID }}/vault"
#  roles:
#    - { role: project_restore, DATA_NAME_VAR: search-basis, DATA_URI: /api/search-basis }
