---
# Label: ansible_project_deployment_config
# Title: create the Ansible template for the project deployment config in OpenShift
# Mission: create the Ansible template for the project deployment config in OpenShift
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
spec:
  replicas: 1
  selector:
    app: opendatapolicing
    deploymentconfig: opendatapolicing
  template:
    metadata:
      labels:
        app: opendatapolicing
        deploymentconfig: opendatapolicing
    spec:
      containers:
        - imagePullPolicy: Always
          name: opendatapolicing
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8081
              name: cluster
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
          resources:
            limits:
              memory: 1.6Gi
          env:
            - name: AUTH_REALM
              valueFrom:
                secretKeyRef:
                  key: AUTH_REALM
                  name: opendatapolicing-secret
            - name: AUTH_RESOURCE
              valueFrom:
                secretKeyRef:
                  key: AUTH_RESOURCE
                  name: opendatapolicing-secret
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: AUTH_SECRET
                  name: opendatapolicing-secret
            - name: AUTH_HOST_NAME
              valueFrom:
                secretKeyRef:
                  key: AUTH_HOST_NAME
                  name: opendatapolicing-secret
            - name: AUTH_PORT
              valueFrom:
                secretKeyRef:
                  key: AUTH_PORT
                  name: opendatapolicing-secret
            - name: AUTH_SSL
              valueFrom:
                secretKeyRef:
                  key: AUTH_SSL
                  name: opendatapolicing-secret
            - name: AUTH_TOKEN_URI
              value: "{{AUTH_TOKEN_URI}}"
            - name: EMAIL_AUTH
              valueFrom:
                secretKeyRef:
                  key: EMAIL_AUTH
                  name: opendatapolicing-secret
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  key: EMAIL_FROM
                  name: opendatapolicing-secret
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  key: EMAIL_HOST
                  name: opendatapolicing-secret
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: EMAIL_PASSWORD
                  name: opendatapolicing-secret
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  key: EMAIL_PORT
                  name: opendatapolicing-secret
            - name: EMAIL_SSL
              valueFrom:
                secretKeyRef:
                  key: EMAIL_SSL
                  name: opendatapolicing-secret
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: EMAIL_USERNAME
                  name: opendatapolicing-secret
            - name: JDBC_HOST
              valueFrom:
                secretKeyRef:
                  key: JDBC_HOST
                  name: opendatapolicing-secret
            - name: JDBC_PORT
              valueFrom:
                secretKeyRef:
                  key: JDBC_PORT
                  name: opendatapolicing-secret
            - name: JDBC_DATABASE
              valueFrom:
                secretKeyRef:
                  key: JDBC_DATABASE
                  name: opendatapolicing-secret
            - name: JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  key: JDBC_USERNAME
                  name: opendatapolicing-secret
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: JDBC_PASSWORD
                  name: opendatapolicing-secret
            - name: SSL_PASSTHROUGH
              valueFrom:
                secretKeyRef:
                  key: SSL_PASSTHROUGH
                  name: opendatapolicing-secret
            - name: SSL_ALIAS
              valueFrom:
                secretKeyRef:
                  key: SSL_ALIAS
                  name: opendatapolicing-secret
            - name: SSL_JKS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SSL_JKS_PASSWORD
                  name: opendatapolicing-secret
            - name: SSL_JKS_PATH
              valueFrom:
                secretKeyRef:
                  key: SSL_JKS_PATH
                  name: opendatapolicing-secret
            - name: SSL_KEYSTORE_PATH
              valueFrom:
                secretKeyRef:
                  key: SSL_KEYSTORE_PATH
                  name: opendatapolicing-secret
            - name: ACS_API_KEY
              valueFrom:
                secretKeyRef:
                  key: ACS_API_KEY
                  name: opendatapolicing-secret

            - name: FTP_SYNC_HOST_NAME
              valueFrom:
                secretKeyRef:
                  key: FTP_SYNC_HOST_NAME
                  name: opendatapolicing-secret
            - name: FTP_SYNC_PORT
              valueFrom:
                secretKeyRef:
                  key: FTP_SYNC_PORT
                  name: opendatapolicing-secret
            - name: FTP_SYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  key: FTP_SYNC_USERNAME
                  name: opendatapolicing-secret
            - name: FTP_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: FTP_SYNC_PASSWORD
                  name: opendatapolicing-secret
            - name: FTP_SYNC_REMOTE_PATH
              valueFrom:
                secretKeyRef:
                  key: FTP_SYNC_REMOTE_PATH
                  name: opendatapolicing-secret

            - name: OPENSHIFT_SERVICE
              value: "opendatapolicing"
            - name: CLUSTER_PORT
              value: "8081"
            - name: ZOOKEEPER_HOST_NAME
              value: "{{ZOOKEEPER_HOST_NAME}}"
            - name: ZOOKEEPER_PORT
              value: "{{ZOOKEEPER_PORT}}"
            - name: SOLR_HOST_NAME
              value: "{{SOLR_HOST_NAME}}"
            - name: SOLR_PORT
              value: "{{SOLR_PORT}}"
            - name: SOLR_URL
              value: "http://{{SOLR_HOST_NAME}}:{{SOLR_PORT}}/solr/{{PROJECT_SOLR_COLLECTION}}"
            - name: SITE_HOST_NAME
              value: "{{PROJECT_SITE_HOST_NAME_ENUS}}"
            - name: SITE_PORT
              value: "{{PROJECT_SITE_PORT}}"
            - name: SITE_BASE_URL
              value: "{{PROJECT_SITE_BASE_URL_ENUS}}"
            - name: NUMBER_EXECUTORS
              value: "{{PROJECT_NUMBER_EXECUTORS}}"
            - name: STATIC_BASE_URL
              value: "{{PROJECT_STATIC_BASE_URL}}"
            - name: STATIC_PATH
              value: "{{PROJECT_STATIC_PATH}}"
            - name: SITE_ZONE
              value: "{{PROJECT_SITE_ZONE_ENUS}}"
            - name: JAVA_MAIN_CLASS
              value: "{{PROJECT_JAVA_MAIN_CLASS_ENUS}}"

            - name: API_COUNTER_PAUSE
              value: "{{API_COUNTER_PAUSE}}"
            - name: API_COUNTER_RESUME
              value: "{{API_COUNTER_RESUME}}"
            - name: API_COUNTER_FETCH
              value: "{{API_COUNTER_FETCH}}"
            - name: ENABLE_IMPORT_DATA
              value: "{{ENABLE_IMPORT_DATA}}"
            - name: TIMER_DB_SOLR_SYNC_IN_SECONDS
              value: "{{TIMER_DB_SOLR_SYNC_IN_SECONDS}}"
            - name: ENABLE_DB_SOLR_SYNC
              value: "{{ENABLE_DB_SOLR_SYNC}}"
            - name: ENABLE_DB_SOLR_SYNC_TrafficContraband
              value: "{{ENABLE_DB_SOLR_SYNC_TrafficContraband}}"
            - name: ENABLE_DB_SOLR_SYNC_SearchBasis
              value: "{{ENABLE_DB_SOLR_SYNC_SearchBasis}}"
            - name: ENABLE_DB_SOLR_SYNC_TrafficSearch
              value: "{{ENABLE_DB_SOLR_SYNC_TrafficSearch}}"
            - name: ENABLE_DB_SOLR_SYNC_TrafficPerson
              value: "{{ENABLE_DB_SOLR_SYNC_TrafficPerson}}"
            - name: ENABLE_DB_SOLR_SYNC_TrafficStop
              value: "{{ENABLE_DB_SOLR_SYNC_TrafficStop}}"
            - name: ENABLE_DB_SOLR_SYNC_SiteAgency
              value: "{{ENABLE_DB_SOLR_SYNC_SiteAgency}}"
            - name: ENABLE_REFRESH_DATA
              value: "{{ENABLE_REFRESH_DATA}}"
            - name: ENABLE_REFRESH_DATA_TrafficContraband
              value: "{{ENABLE_REFRESH_DATA_TrafficContraband}}"
            - name: ENABLE_REFRESH_DATA_SearchBasis
              value: "{{ENABLE_REFRESH_DATA_SearchBasis}}"
            - name: ENABLE_REFRESH_DATA_TrafficSearch
              value: "{{ENABLE_REFRESH_DATA_TrafficSearch}}"
            - name: ENABLE_REFRESH_DATA_TrafficPerson
              value: "{{ENABLE_REFRESH_DATA_TrafficPerson}}"
            - name: ENABLE_REFRESH_DATA_TrafficStop
              value: "{{ENABLE_REFRESH_DATA_TrafficStop}}"
            - name: TIMER_DB_SOLR_SYNC_IN_SECONDS
              value: "{{TIMER_DB_SOLR_SYNC_IN_SECONDS}}"
            - name: ENABLE_FTP_SYNC
              value: "{{ENABLE_FTP_SYNC}}"
            - name: ENABLE_FTP_SYNC_TrafficStop
              value: "{{ENABLE_FTP_SYNC_TrafficStop}}"
            - name: ENABLE_FTP_SYNC_TrafficPerson
              value: "{{ENABLE_FTP_SYNC_TrafficPerson}}"
            - name: ENABLE_FTP_SYNC_TrafficSearch
              value: "{{ENABLE_FTP_SYNC_TrafficSearch}}"
            - name: ENABLE_FTP_SYNC_SearchBasis
              value: "{{ENABLE_FTP_SYNC_SearchBasis}}"
            - name: ENABLE_FTP_SYNC_TrafficContraband
              value: "{{ENABLE_FTP_SYNC_TrafficContraband}}"
            - name: FTP_SYNC_PATH_ZIP
              value: "{{FTP_SYNC_PATH_ZIP}}"
            - name: FTP_SYNC_PATH_TrafficStop
              value: "{{FTP_SYNC_PATH_TrafficStop}}"
            - name: FTP_SYNC_PATH_TrafficPerson
              value: "{{FTP_SYNC_PATH_TrafficPerson}}"
            - name: FTP_SYNC_PATH_TrafficSearch
              value: "{{FTP_SYNC_PATH_TrafficSearch}}"
            - name: FTP_SYNC_PATH_TrafficContraband
              value: "{{FTP_SYNC_PATH_TrafficContraband}}"
            - name: FTP_SYNC_PATH_TrafficSearchBasis
              value: "{{FTP_SYNC_PATH_TrafficSearchBasis}}"
            - name: FTP_MAX_RECORD_SIZE
              value: "{{FTP_MAX_RECORD_SIZE}}"
          volumeMounts:
            - mountPath: /opt/keystore
              name: volume-keystore
              readOnly: true
            - mountPath: /opt/static/template
              name: volume-template
              readOnly: true
            - mountPath: "{{ FTP_SYNC_PATH }}"
              name: volume-ftp
      volumes:
        - name: volume-keystore
          secret:
            defaultMode: 420
            secretName: opendatapolicing-keystore
        - name: volume-template
          configMap:
            defaultMode: 420
            name: opendatapolicing-template
        - name: volume-ftp
          persistentVolumeClaim:
            claimName: opendatapolicing-persistent-volume-claim-ftp
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - opendatapolicing
        from:
          kind: ImageStreamTag
          name: 'opendatapolicing:latest'
          namespace: {{PROJECT_NAMESPACE}}
      type: ImageChange
    - type: ConfigChange
