---
# Label: ansible_project_secret
# Title: create the Ansible secret for the project in OpenShift
# Mission: create the Ansible secret for the project in OpenShift
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment

apiVersion: v1
stringData:
  JDBC_URL: "jdbc:postgresql://postgres.{{POSTGRES_NAMESPACE}}.svc:5432/{{POSTGRES_DB_NAME}}"
  JDBC_USERNAME: "{{POSTGRES_DB_USER}}"
  JDBC_PASSWORD: "{{POSTGRES_DB_PASSWORD}}"
  JDBC_DATABASE: "{{POSTGRES_DB_NAME}}"
  JDBC_HOST: "{{POSTGRES_HOST_NAME}}"
  JDBC_PORT: "{{POSTGRES_PORT}}"
  AUTH_REALM: "{{AUTH_REALM}}"
  AUTH_RESOURCE: "{{AUTH_RESOURCE}}"
  AUTH_SECRET: "{{AUTH_SECRET}}"
  AUTH_HOST_NAME: "{{AUTH_HOST_NAME}}"
  AUTH_PORT: "{{AUTH_PORT}}"
  AUTH_SSL: "{{AUTH_SSL}}"
  AUTH_REALM: "{{AUTH_REALM}}"
  EMAIL_HOST: "{{EMAIL_HOST_NAME}}"
  EMAIL_PORT: "{{EMAIL_PORT}}"
  EMAIL_FROM: "{{EMAIL_FROM}}"
  EMAIL_SSL: "{{EMAIL_SSL}}"
  EMAIL_AUTH: "{{EMAIL_AUTH}}"
  EMAIL_USERNAME: "{{EMAIL_USER}}"
  EMAIL_PASSWORD: "{{EMAIL_PASSWORD}}"
  SSL_PASSTHROUGH: "{{ SSL_PASSTHROUGH | default(false) }}"
  SSL_KEYSTORE_PATH: "{{SSL_KEYSTORE_PATH}}"
  SSL_JKS_PATH: "{{SSL_JKS_PATH}}"
  SSL_ALIAS: "{{SSL_ALIAS}}"
  SSL_JKS_PASSWORD: "{{SSL_JKS_PASSWORD}}"
  ACS_API_KEY: "{{ACS_API_KEY}}"
  FTP_SYNC_HOST_NAME: "{{FTP_SYNC_HOST_NAME}}"
  FTP_SYNC_PORT: "{{FTP_SYNC_PORT}}"
  FTP_SYNC_USERNAME: "{{FTP_SYNC_USERNAME}}"
  FTP_SYNC_PASSWORD: "{{FTP_SYNC_PASSWORD}}"
  FTP_SYNC_REMOTE_PATH: "{{FTP_SYNC_REMOTE_PATH}}"
kind: Secret
type: Opaque
